sudo: true

services:
  - docker

matrix:
  include:
    - language: python
      python: 2.7
      install:
        - sudo ./install-travis.sh
      script:
        - sudo ./test-travis.sh
    - language: python
      python: 3.6
      install:
        - sudo ./install-travis.sh
      script:
        - sudo ./test-travis.sh
    - language: r
      dist: trusty
      cache: packages
      r_packages:
        - covr
      before_install:
        - export NOT_CRAN=true
        - export MLFLOW_TEST_REQUIREMENTS=false
        - sudo ./install-travis.sh
        - export MLFLOW_HOME=$(pwd)
        - cd R/mlflow
      script:
        - cd ../..
        - R CMD build R/mlflow/.
        - R CMD check --no-build-vignettes --no-manual --no-tests cloudml*tar.gz
        - Rscript R/mlflow/.travis.R
      after_success:
        - Rscript -e 'covr::codecov()'
